//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int B_id { get; set; }
        public string U_id { get; set; }
        public string P_id { get; set; }
        public string P_qty { get; set; }
        public string O_status { get; set; }
        public string O_id { get; set; }
        public string B_first { get; set; }
        public string B_last { get; set; }
        public string B_number { get; set; }
        public string B_address { get; set; }
        public string B_city { get; set; }
        public string B_zip { get; set; }
        public string createdAt { get; set; }
        public string updatedAt { get; set; }
        public string isReview { get; set; }
    }
}
