//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int C_id { get; set; }
        public string C_name { get; set; }
        public string createdAt { get; set; }
        public string updatedAt { get; set; }
    }
}
