//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int P_id { get; set; }
        public string P_name { get; set; }
        public string P_price { get; set; }
        public string P_dprice { get; set; }
        public string P_cat { get; set; }
        public string P_img1 { get; set; }
        public string P_img2 { get; set; }
        public string P_img3 { get; set; }
        public string P_stock { get; set; }
        public string P_desc { get; set; }
        public string createdAt { get; set; }
        public string updatedAt { get; set; }
    }
}
