//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int S_id { get; set; }
        public string S_img { get; set; }
        public string S_name { get; set; }
        public string S_desc { get; set; }
        public string S_status { get; set; }
        public string createdAt { get; set; }
        public string updatedAt { get; set; }
    }
}
